name: proj
description: "A new Flutter project."

# Prevents the package from being accidentally published to pub.dev.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  readmore: ^2.2.0 # Additional dependency for "Read More" functionality

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 # Recommended linting package

flutter:
  # Ensure Material Icons font is included.
  uses-material-design: true

  # Adding assets to your application.
  assets:
    - assets/images/bg_liquid.png
    - assets/images/legend_logo.jpg
    - assets/images/legend1.jpg
    - assets/images/legend2.jpg
    - assets/images/legend3.jpg
    - assets/images/legend4.jpg
    - assets/images/ori_logo.png
    - assets/images/ori1.jpg
    - assets/images/ori2.jpg
    - assets/images/ori3.jpg
    - assets/images/ori4.jpg
    - assets/images/ori5.jpg
    - assets/images/rl_logo.png
    - assets/images/rl1.jpg
