name: proj
description: "A new Flutter project."

# Prevents the package from being accidentally published to pub.dev.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  readmore: ^2.2.0 # Additional dependency

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 # Recommended linting package

flutter:
  # Ensure Material Icons font is included.
  uses-material-design: true

  # Adding assets to your application.
  #assets: 
    #- images/bg_liquid.png
    #- images/legend_logo.jpg
    #- images/legend1.jpg
    #- images/legend2.jpg
    #- images/legend3.jpg
    #- images/legend4.jpg
    #- images/ori_logo.png
    #- images/ori1.jpg
    #- images/ori2.jpg
    #- images/ori3.jpg
    #- images/ori4.jpg
    #- images/ori5.jpg
    #- images/rl_logo.png
    #- images/rl1.jpg
    # Remove these two lines if they are not needed
    # - images/ # Empty directory entry (not needed)
    # - images/ # Empty directory entry (not needed)

